## Numpy

In [1]:
import numpy as np

In [2]:
a1=np.array([1,2,3,4,5,6],)
print(a1)
print(a1.ndim)

[1 2 3 4 5 6]
1


In [3]:
a2=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(a2)
print(a2.ndim)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
2


In [4]:
l=[1,2,3,4,5,6]
a3=np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[11,12,13,14,15],[16,17,18,19,20]]])

print(a3)
print(a3.ndim)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]
3


In [5]:
#Accessing the elements

In [6]:
a1[0]

1

In [7]:
a2[0,4]

5

In [8]:
a2[1,-1]

12

In [9]:
a3

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

In [10]:
a3[0]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [11]:
a3[1]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [12]:
a3[1,0,1]

12

In [13]:
a33=np.array([[[99,88,77]]])
a33

array([[[99, 88, 77]]])

In [68]:
print(a33[0])
#THis is 3D array which contains ONE 1x3 matrix, which contains ONE array which contains THREE scalars
print(a33.shape)

[[99 88 77]]
(1, 1, 3)


In [15]:
#a33[1] - error

### Slicing

In [16]:
a1[::]

array([1, 2, 3, 4, 5, 6])

In [17]:
a1[1:4]

array([2, 3, 4])

In [69]:
a2

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [18]:
a2[0,1:2]

array([2])

In [19]:
a2[0:2,3:6]

array([[ 4,  5,  6],
       [10, 11, 12]])

In [20]:
a3

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

In [21]:
a3[1,0,3:6]

array([14, 15])

In [22]:
a3[:,:,3:6]

array([[[ 4,  5],
        [ 9, 10]],

       [[14, 15],
        [19, 20]]])

In [23]:
a3[0:2,0:4,3:6]

array([[[ 4,  5],
        [ 9, 10]],

       [[14, 15],
        [19, 20]]])

### Random values

In [70]:
"""Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.
"""
np.random.rand(3,3)

array([[0.42891466, 0.01830837, 0.40950348],
       [0.11817157, 0.76096981, 0.50194498],
       [0.91632995, 0.95753944, 0.1826759 ]])

In [71]:
"""
randint(low, high=None, size=None, dtype=int)
Return random integers from `low` (inclusive) to `high` (exclusive)."""
np.random.randint(3,100,10)

array([60, 37, 96, 93, 88, 31, 29, 34, 53, 35])

In [72]:
np.random.randint(10)
#randint(low, high=None, size=None, dtype=int)

7

In [73]:
r=np.random.randint(3,100,10)
r

array([24, 82, 25, 60, 85, 67, 56, 40, 96, 21])

In [27]:
r=np.random.randint(3,100,(3,3,10))
r

array([[[44, 25, 96, 14, 75, 34, 78, 63, 98, 95],
        [55, 74, 96, 33, 99, 74, 47, 38, 14, 83],
        [36, 13, 23, 10,  8, 82, 40, 46, 31, 13]],

       [[75, 22, 48,  3, 80, 75, 78, 91, 69,  3],
        [13, 21, 41, 65, 11, 98, 93, 28, 76, 64],
        [69, 97, 63, 11, 38, 31, 66, 76, 78, 88]],

       [[25, 36, 76, 19, 37, 21, 45, 46, 36, 94],
        [22, 92, 96, 93, 78, 92, 85, 97,  8, 65],
        [74, 65, 56, 71, 27, 61, 76, 83, 81, 82]]])

In [28]:
print(a3.shape)
print(a3)
#Output:(2,2,5)-(number of arrays, number of rows, number of columns/elements)

(2, 2, 5)
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]


In [29]:
a3.shape

(2, 2, 5)

In [30]:
a3.reshape(1,5,4)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20]]])

## zeros

In [31]:
import numpy as np
import pandas as pd
np.zeros(5)
#Return a new array of given shape and type, filled with zeros.


array([0., 0., 0., 0., 0.])

In [32]:
np.zeros((4,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [74]:
np.zeros((2,4,5),dtype=int)

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]])

In [33]:
#Return evenly spaced values within a given interval.
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [34]:
c1=np.arange(0,10).reshape(2,5)
c1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [35]:
np.zeros_like(c1)
#Return an array of zeros with the same shape and type as a given array.

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

## Ones

In [36]:
o=np.ones((3,2))
o

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [37]:
np.ones_like(o,dtype=int)

array([[1, 1],
       [1, 1],
       [1, 1]])

## Full

In [76]:
np.full((5,5),50)
#Return a new array of given shape and type, filled with `fill_value`.

array([[50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50]])

In [77]:
np.full_like(c1,50)

array([[50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50]])

## eye

In [40]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [41]:
np.eye(5,5)
#Return a 2-D array with ones on the diagonal and zeros elsewhere.

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [42]:
np.eye(3,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [43]:
np.eye(10,k=4)

array([[0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [44]:
np.eye(5,10,k=4)

array([[0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])

## Array with numerical range

In [45]:
list(range(0,10,2))
#This can return ONLY int objects

[0, 2, 4, 6, 8]

In [46]:
np.arange(0,10)

#arange is faster than range due to memory allocation

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
np.arange(1,10,0.5)
#here floats can also be obtained

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [48]:
type(range(0,10))

range

In [49]:
type(np.arange(0,10))

numpy.ndarray

## linespace

In [50]:
np.linspace(1,100)

array([  1.        ,   3.02040816,   5.04081633,   7.06122449,
         9.08163265,  11.10204082,  13.12244898,  15.14285714,
        17.16326531,  19.18367347,  21.20408163,  23.2244898 ,
        25.24489796,  27.26530612,  29.28571429,  31.30612245,
        33.32653061,  35.34693878,  37.36734694,  39.3877551 ,
        41.40816327,  43.42857143,  45.44897959,  47.46938776,
        49.48979592,  51.51020408,  53.53061224,  55.55102041,
        57.57142857,  59.59183673,  61.6122449 ,  63.63265306,
        65.65306122,  67.67346939,  69.69387755,  71.71428571,
        73.73469388,  75.75510204,  77.7755102 ,  79.79591837,
        81.81632653,  83.83673469,  85.85714286,  87.87755102,
        89.89795918,  91.91836735,  93.93877551,  95.95918367,
        97.97959184, 100.        ])

In [51]:
np.linspace(1,100,25)
#Return evenly spaced numbers over a specified interval.

array([  1.   ,   5.125,   9.25 ,  13.375,  17.5  ,  21.625,  25.75 ,
        29.875,  34.   ,  38.125,  42.25 ,  46.375,  50.5  ,  54.625,
        58.75 ,  62.875,  67.   ,  71.125,  75.25 ,  79.375,  83.5  ,
        87.625,  91.75 ,  95.875, 100.   ])

In [52]:
np.linspace(1,100,25,endpoint=False)

array([ 1.  ,  4.96,  8.92, 12.88, 16.84, 20.8 , 24.76, 28.72, 32.68,
       36.64, 40.6 , 44.56, 48.52, 52.48, 56.44, 60.4 , 64.36, 68.32,
       72.28, 76.24, 80.2 , 84.16, 88.12, 92.08, 96.04])

In [53]:
np.linspace(1,100,25,retstep=True)
#Returns stepsize at end  here ex.4.125

(array([  1.   ,   5.125,   9.25 ,  13.375,  17.5  ,  21.625,  25.75 ,
         29.875,  34.   ,  38.125,  42.25 ,  46.375,  50.5  ,  54.625,
         58.75 ,  62.875,  67.   ,  71.125,  75.25 ,  79.375,  83.5  ,
         87.625,  91.75 ,  95.875, 100.   ]),
 4.125)

## logspace

In [54]:
np.logspace(1,100,25,base=2,endpoint=False)

array([2.00000000e+00, 3.11249583e+01, 4.84381515e+02, 7.53817723e+03,
       1.17312726e+05, 1.82567685e+06, 2.84120580e+07, 4.42162061e+08,
       6.88113785e+09, 1.07087564e+11, 1.66654799e+12, 2.59356184e+13,
       4.03622520e+14, 6.28136706e+15, 9.77536439e+16, 1.52128905e+18,
       2.36750291e+19, 3.68442146e+20, 5.73387323e+21, 8.92332826e+22,
       1.38869110e+24, 2.16114763e+25, 3.36328150e+26, 5.23409982e+27,
       8.14555693e+28])

## AXIS in array
for numpy:

    axis 0: means through columns
    axis 1:means through rows

In [55]:
a3=np.array([[[1,2,3,4]]])
a3.shape

(1, 1, 4)

In [56]:
b2=np.array([[55,96,14],[23,410,96]])
print(b2)

[[ 55  96  14]
 [ 23 410  96]]


In [57]:
np.sort(b2,axis=0) #Columnwise

array([[ 23,  96,  14],
       [ 55, 410,  96]])

In [58]:
np.sort(b2, axis=1) #Row wise

array([[ 14,  55,  96],
       [ 23,  96, 410]])

In [59]:
bb2=np.array([[42,36,98]])
bb2

array([[42, 36, 98]])

In [60]:
np.sort(bb2, axis=1)

array([[36, 42, 98]])

In [61]:
np.sort(bb2, axis=0)

array([[42, 36, 98]])

## Datatypes in array

    i=int
    f=float
    s=string
    u=unicode string
    m=timedelta
    M=timedate
    o=object
    v=void

In [62]:
a=np.array([1,10,20,30],dtype='float')
a

array([ 1., 10., 20., 30.])

## copy()
-if change in one, No change in other

In [63]:
v=np.array([1,2,3])
c=np.copy(v)
c

array([1, 2, 3])

In [64]:
c[0]=99
print("c", c)
print("v", v)

c [99  2  3]
v [1 2 3]


## view()
-creates a reference of existing array

-if change in one, there is change in other

In [65]:
v=np.array([1,2,3])
c=v.view()
c

array([1, 2, 3])

In [66]:
c[0]=99
print("c", c)
print("v", v)

c [99  2  3]
v [99  2  3]


### hstack

### vstack